name: Sync LeetCode to GitHub

on:
  workflow_dispatch: # Adds a manual sync button
  schedule:
    - cron: '0 0 * * *' # Automatically runs every night

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync Action
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-solutions
