name: Sync LeetCode to GitHub

on:
  workflow_dispatch: # Allows manual trigger button
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync Action
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-solutions
